# yggdrasil -genconf > /etc/yggdrasil/yggdrasil.conf

{
  # 您的私钥.请勿与任何人分享！
  PrivateKey: XXXX

  # 出站对等连接字符串列表（例如 tls://a.b.c.d:e 或
  # socks://a.b.c.d:e/f.g.h.i:j）.连接字符串可包含选项, 
  # 参见 https://yggdrasil-network.github.io/configurationref.html#peers.
  # Yggdrasil 没有引导节点的概念——所有网络流量
  # 都将通过对等连接传输.因此请确保只与附近
  # 具有良好连接性和低延迟的节点建立对等关系.避免添加
  # 远距离国家的节点作为对等端, 因为这会显著降低您
  # 节点的连接性和性能.
  Peers: [
    tcp://ygg5.mk16.de:1337?key=0000009611ae5391dc0aceea9f3fa6a0dc1279f4306059339e84bfb8b74d2f9b
    tls://ygg5.mk16.de:1338?key=0000009611ae5391dc0aceea9f3fa6a0dc1279f4306059339e84bfb8b74d2f9b
    quic://ygg5.mk16.de:1339?key=0000009611ae5391dc0aceea9f3fa6a0dc1279f4306059339e84bfb8b74d2f9b
    ws://ygg5.mk16.de:1340?key=0000009611ae5391dc0aceea9f3fa6a0dc1279f4306059339e84bfb8b74d2f9b
    tcp://ygg-tw.lxak.net:8879
    tls://ygg-tw.lxak.net:8880
    tls://cowgl.tech:1337 
  ]

  # 按源接口组织的 URI 格式出站对等连接字符串列表, 
  # 例如 { "eth0": [ "tls://a.b.c.d:e" ] }.
  # 仅当您的机器是多宿主且希望在不同接口上
  # 建立出站对等连接时, 才应使用此选项.
  # 否则应使用 "Peers".
  InterfacePeers: {}

  # 用于入站连接的监听地址.您需要添加
  # 监听器以便接受来自非本地节点的入站对等连接.
  # 如果只希望建立出站对等关系, 则不需要此项.
  # 多播对等发现功能无论此处设置何种监听器都会工作.
  # 每个监听器应按上述 URI 格式指定, 例如
  # tls://0.0.0.0:0 或 tls://[::]:0 以监听所有接口.
  Listen: []

  # 多播对等发现应在哪些接口上启用的配置.
  # Regex 是一个正则表达式, 用于匹配接口名称, 
  # 接口使用第一个匹配到的配置.
  # Beacon 控制您的节点是否向其他节点通告其
  # 存在, 而 Listen 控制您的节点是否监听
  # 并尝试连接到其他通告节点.更多支持的选项请参见
  # https://yggdrasil-network.github.io/configurationref.html#multicastinterfaces
  MulticastInterfaces: [
    {
      Regex: .*
      Beacon: true
      Listen: true
      Password: ""
    }
  ]

  # 允许建立入站对等连接的节点公钥列表.
  # 如果留空/未定义, 则默认允许所有连接.
  # 这不影响出站对等连接, 也不影响通过多播发现的链路本地节点.
  # 警告: 这不是防火墙, 也不限制谁可以访问
  # 您机器上开放的端口或运行的服务！
  AllowedPublicKeys: []

  # TUN 适配器的本地网络接口名称, 或使用 "auto" 自动
  # 选择接口, 或使用 "none" 在没有 TUN 的情况下运行.
  IfName: auto

  # 本地 TUN 接口的最大传输单元（MTU）大小.
  # 默认值是您平台支持的最大大小.最小
  # 可能值为 1280.
  IfMTU: 65535

  # 默认情况下, nodeinfo 包含一些默认信息, 包括平台、
  # 架构和 Yggdrasil 版本.这些信息有助于网络调查
  # 和诊断网络路由问题.启用 nodeinfo 隐私可以防止
  # 发送这些信息, 使得仅当在 "NodeInfo" 中指定时才会返回相应项.
  NodeInfoPrivacy: false

  # 可选的节点信息.这必须是一个 { "键": "值", ... } 映射
  # 或设置为 null.这完全是可选的, 但如果设置了, 
  # 则整个网络在请求时都可以看到.
  NodeInfo: {}
}