#-#-#-#-#-#-#-#-#-#-#-  ircServer链接配置  -#-#-#-#-#-#-#-#-#-#
# 启用监听
<bind port="7001" type="servers" sslprofile="Servers">
# 连接服务器2
<link name="irc2af.arkfuture.irc"
      ipaddr="172.27.143.136"
      port="7001"
      allowmask="*"
      timeout="1m"
      statshidden="no"
      hidden="no"
      sslprofile="Servers"
      fingerprint="879AF02AD666227E2B840ED444DE48D044D429B05DB4E964068F90054671F036"
      sendpass="FEhZyMU8DQX3A3MPApTF"
      recvpass="FEhZyMU8DQX3A3MPApTF">

# 自动连接
<autoconnect bootperiod="15s" period="30s" server="irc2af.arkfuture.irc">