serverAddr = "frp.freefrp.net"
serverPort = "7000"
auth.method = "token"
auth.token = "freefrp.net"

[proxiex]
name = "AIFREC"
type = "tcp"
localIp = "127.0.0.1"
localPort = "6667"
remotePort = "55555"