/*
 * help 
 *
 * 提供 generic/help 命令.
 *
 * 通用帮助命令, 可用于任何客户端.
 */
module { name = "help" }
 
/*
 * m_dns 
 *
 * 添加 DNS 协议支持. 该模块本身无独立功能,
 * 但 m_dnsbl 和 os_dns 等其他模块依赖此模块.
 */
module 
{
	name = "m_dns"
 
	/*
	 * 用于解析主机名的域名服务器, 必须是 IP 或解析器配置文件.
	 * 以下配置在类 UNIX 系统通常有效. Windows 用户需通过 ipconfig /all 
	 * 获取域名服务器 IP 并填写此处.
	 */
	nameserver = "/etc/resolv.conf" 
	#nameserver = "127.0.0.1"
 
	/*
	 * DNS 查询超时等待时间(秒).
	 */
	timeout = 5 
}
 
/*
 * m_dnsbl 
 *
 * 支持可配置的 DNS 黑名单检查连接用户. 
 * 若用户在黑名单中, 将立即被禁止. 此模块对防范僵尸攻击至关重要.
 */
#module 
{
	name = "m_dnsbl"
 
	/*
	 * 若启用, Services 会在连接其上行服务器时检查客户端 DNSBL. 
	 * 不推荐此操作, 在大型网络中会发起大量 DNS 查询.
	 * 虽然 Services 不受严重影响, 但您的域名服务器/DNSBL 可能受影响.
	 */
	check_on_connect = no 
 
	/*
	 * 若启用, Services 会在网络突发恢复时检查客户端. 
	 * 可能同时发起大量 DNS 查询. 
	 * 虽然 Services 不受严重影响, 但您的域名服务器/DNSBL 可能受影响.
	 */
	check_on_netburst = no 
 
	/*
	 * 若启用, OperServ 会将 DNSBL 发现的客户端加入 akill 列表. 
	 * 否则 OperServ 仅发送临时 G/K-line 至 IRCd 后不再处理. 
	 * 当 akill 列表被僵尸程序填满时很有用.
	 */
	add_to_akill = yes 
 
	blacklist 
	{
		/* 黑名单名称. */
		name = "rbl.efnetrbl.org" 
 
		/* 禁止持续时间. */
		time = 4h 
 
		/* akill 原因.
		 * %n : 用户昵称 
		 * %u : 用户标识(ident/username)
		 * %g : 用户真实姓名 
		 * %h : 用户主机名 
		 * %i : 用户 IP 
		 * %r : 回复原因(下方配置). 未配置则为空 
		 * %N : networkinfo:networkname 中设置的网络名称 
		 */
		reason = "You are listed in the EFnet RBL, visit https://rbl.efnetrbl.org/?i=%i  for info"
 
		/* 需禁止的回复及其原因. 未配置回复时, 所有回复均被禁止. */
		reply 
		{
			code = 1 
			reason = "Open Proxy"
		}
 
		#reply 
		{
			code = 2 
			reason = "spamtrap666"
		}
 
		#reply 
		{
			code = 3 
			reason = "spamtrap50"
		}
 
		reply 
		{
			code = 4 
			reason = "Drones / Flooding"
 
			/*
			 * 若设置, 在结果返回时已通过服务认证的用户不会被禁止.
			 */
			#allow_account = yes 
		}
	}
 
	#blacklist 
	{
		name = "dnsbl.dronebl.org" 
		time = 4h 
		reason = "You have a host listed in the DroneBL. For more information, visit https://dronebl.org/lookup_branded?ip=%i&network=%N" 
	}
 
	/* 豁免本地主机免于 DNSBL 检查 */
	exempt { ip = "127.0.0.0/8" }
}
 
/*
 * m_helpchan 
 *
 * 为指定帮助频道中的 OP 用户授予 +h (helpop) 用户模式.
 */
module 
{
	name = "m_helpchan"
 
	helpchannel = "#help"
}
 
 
/*
 * m_sasl 
 *
 * 一些 IRC 服务器允许 "SASL" 认证, 让用户在 IRCd 用户注册过程中向服务进行身份验证.
 * 如果加载此模块, 服务将允许用户通过此机制进行认证. 支持的机制包括:
 * PLAIN, EXTERNAL.
 */
module { name = "m_sasl" }


/*
 * m_redis
 *
 * 此模块允许其他模块使用 Redis.
 */
#module
{
	name = "m_redis"

	/* 一个 Redis 数据库 */
	redis
	{
		/* 这项服务的名称 */
		name = "redis/main"

		/*
		 * 要使用的 Redis 数据库. 新连接数默认为 0.
		 */
		db = 0

		ip = "127.0.0.1"
		port = 6379
	}
}


/*
 * m_rewrite
 *
 * 允许重写发送到/来自客户端的命令.
 */
#module { name = "m_rewrite" }
#command
{
	service = "ChanServ"; name = "CLEAR"; command = "rewrite"

	/* .应用此模块. */
	rewrite = true

	/* 要匹配的源消息. $可以用来匹配任何东西. */
	rewrite_source = "CLEAR $ USERS"

	/*
	 * 要将源消息重写到的消息. 
	 * $后面跟一个数字, 例如$0被source_message中从0开始的第几个字替换.
	 */
	rewrite_target = "KICK $1 *"

	/*
	 * 命令描述.
	 * 这只显示在帮助的输出中. 注释此选项以防止该命令显示在HELP命令中.
	 * 
	 */
	rewrite_description = "Clears all users from a channel"
}


/*
 * m_httpd
 *
 * 允许服务提供网页.该模块本身不执行任何有用操作.
 *
 * 请注意, 使用此模块将允许用户获取您服务的 IP 地址.
 * 为避免这种情况, 我们建议使用反向代理或隧道.
 */
#module
{
	name = "m_httpd"

	httpd
	{
		/* 此服务的名称. */
		name = "httpd/main"

		/* 监听的 IP 地址. */
		ip = "0.0.0.0"

		/* 监听的端口. */
		port = 8080

		/* 与此服务器的连接超时时间. */
		timeout = 30

		/* 使用 SSL 监听.需要 SSL 模块. */
		#ssl = yes

		/* 如果您使用的反向代理会发送下面 extforward_headers 中设置的某个头部
		 * 请将此选项设置为该代理的 IP 地址.
 		 * 这将允许服务通过读取 forwarded-for HTTP 头来获取用户的真实 IP.
		 * 可以指定多个 IP 地址, 使用空格分隔.
		 */
		#extforward_ip = "192.168.0.255 192.168.1.255"

		/* 要查找的头部名称.这些默认值通常可直接使用. */
		extforward_header = "X-Forwarded-For Forwarded-For"
	}
}



/*
 * webcpanel
 *
 * 此模块创建一个 Web 配置面板, 允许用户和操作员执行与通过 IRC 相同的任何任务
 * 如果您使用默认配置, 则可以在运行 Anope 的机器上, 通过 Web 浏览器访问 http://127.0.0.1:8080 来访问此面板
 *
 * 此模块需要 m_httpd.
 */
#module
{
	name = "webcpanel"

	/* 要使用的 Web 服务器. */
	server = "httpd/main";

	/* 要使用的模板. */
	template = "default";

	/* 页面标题. */
	title = "Anope IRC Services";
}
